"""Typed wire contracts for finite semigroup operations."""

from __future__ import annotations

from typing import Self

from pydantic import Field, model_validator

from jacobian._models import StrictModel

MAX_ELEMENTS = 50
MAX_LABEL_LENGTH = 64


class FiniteSemigroup(StrictModel):
    """A finite semigroup: a finite set with an associative binary operation."""

    elements: tuple[str, ...] = Field(min_length=1, max_length=MAX_ELEMENTS)
    multiplication: tuple[tuple[str, ...], ...]

    @model_validator(mode="after")
    def require_valid_semigroup(self) -> Self:
        labels = set(self.elements)
        if len(labels) != len(self.elements):
            raise ValueError("element labels must be distinct")
        for label in self.elements:
            if len(label) > MAX_LABEL_LENGTH:
                raise ValueError("element label exceeds the bounded length budget")
        if len(self.multiplication) != len(self.elements):
            raise ValueError("multiplication table must have one row per element")
        for row in self.multiplication:
            if len(row) != len(self.elements):
                raise ValueError("multiplication table must be square")
            for cell in row:
                if cell not in labels:
                    raise ValueError("every product must be a declared element")
        self._check_associativity(labels)
        return self

    def _check_associativity(self, labels: set[str]) -> None:
        idx = {label: i for i, label in enumerate(self.elements)}
        n = len(self.elements)
        for i in range(n):
            for j in range(n):
                for k in range(n):
                    ij = self.multiplication[i][j]
                    jk = self.multiplication[j][k]
                    left = self.multiplication[idx[ij]][k]
                    right = self.multiplication[i][idx[jk]]
                    if left != right:
                        raise ValueError(
                            f"semigroup must be associative: "
                            f"({self.elements[i]}*{self.elements[j]})*{self.elements[k]} "
                            f"!= {self.elements[i]}*({self.elements[j]}*{self.elements[k]})"
                        )


class PowerProfileRequest(StrictModel):
    """Request the power profile of one element in a finite semigroup."""

    semigroup: FiniteSemigroup
    element: str

    @model_validator(mode="after")
    def require_element_exists(self) -> Self:
        if self.element not in set(self.semigroup.elements):
            raise ValueError("element must be in the semigroup")
        return self


class PowerProfileResult(StrictModel):
    """The power profile of one element in a finite semigroup.

    The supplied semigroup and element are carried on the result so the
    bound model can re-run the exact native kernel and verify the power
    sequence, index, period, idempotent, and cyclic subsemigroup.  ``index``
    is the smallest positive exponent whose power first repeats; ``powers``
    is ``a, a^2, a^3, ...`` in one-based exponent order.
    """

    semigroup: FiniteSemigroup
    element: str
    powers: tuple[str, ...]
    index: int = Field(ge=1)
    period: int = Field(ge=1)
    idempotent: str
    cyclic_subsemigroup: tuple[str, ...]

    @model_validator(mode="after")
    def bind_power_profile(self) -> Self:
        from jacobian.math.finite_semigroups._operations import _power_profile_data

        powers, index, period, idempotent, cyclic = _power_profile_data(
            self.semigroup.elements,
            self.semigroup.multiplication,
            self.element,
        )
        if self.powers != powers:
            raise ValueError("powers must be the exact power sequence of the element")
        if self.index != index:
            raise ValueError("index must be the first repeated power exponent")
        if self.period != period:
            raise ValueError("period must be the power cycle length")
        if self.idempotent != idempotent:
            raise ValueError("idempotent must be the unique idempotent power")
        if self.cyclic_subsemigroup != cyclic:
            raise ValueError(
                "cyclic_subsemigroup must be the exact closure of the element"
            )
        return self


class GeneratedSubsemigroupRequest(StrictModel):
    """Request the subsemigroup generated by a set of elements."""

    semigroup: FiniteSemigroup
    generators: tuple[str, ...] = Field(min_length=1)

    @model_validator(mode="after")
    def require_generators_exist(self) -> Self:
        labels = set(self.semigroup.elements)
        for gen in self.generators:
            if gen not in labels:
                raise ValueError("every generator must be in the semigroup")
        return self


class GeneratedSubsemigroupResult(StrictModel):
    """The subsemigroup generated by a set of elements."""

    generators: tuple[str, ...]
    elements: tuple[str, ...]


class ElementPowerRequest(StrictModel):
    """Request the exact power ``element^exponent`` in a finite semigroup."""

    semigroup: FiniteSemigroup
    element: str
    exponent: int = Field(ge=1)

    @model_validator(mode="after")
    def require_element_exists(self) -> Self:
        if self.element not in set(self.semigroup.elements):
            raise ValueError("element must be in the semigroup")
        return self


class ElementPowerResult(StrictModel):
    """The exact power ``element^exponent`` in a finite semigroup."""

    semigroup: FiniteSemigroup
    element: str
    exponent: int = Field(ge=1)
    power: str

    @model_validator(mode="after")
    def bind_power(self) -> Self:
        from jacobian.math.finite_semigroups._operations import _element_power

        power = _element_power(
            self.semigroup.elements,
            self.semigroup.multiplication,
            self.element,
            self.exponent,
        )
        if self.power != power:
            raise ValueError("power must be the exact iterated product of the element")
        return self


class IdempotentsRequest(StrictModel):
    """Request all idempotent elements ``e`` with ``e*e = e``."""

    semigroup: FiniteSemigroup


class IdempotentsResult(StrictModel):
    """All idempotent elements of a finite semigroup."""

    semigroup: FiniteSemigroup
    idempotents: tuple[str, ...]

    @model_validator(mode="after")
    def bind_idempotents(self) -> Self:
        from jacobian.math.finite_semigroups._operations import _idempotents

        idempotents = _idempotents(
            self.semigroup.elements, self.semigroup.multiplication
        )
        if self.idempotents != idempotents:
            raise ValueError("idempotents must be exactly the elements with e*e = e")
        return self


class PrincipalIdealsRequest(StrictModel):
    """Request the principal ideal of each listed element."""

    semigroup: FiniteSemigroup
    elements: tuple[str, ...] = Field(min_length=1, max_length=MAX_ELEMENTS)

    @model_validator(mode="after")
    def require_elements_exist(self) -> Self:
        labels = set(self.semigroup.elements)
        for element in self.elements:
            if element not in labels:
                raise ValueError("every element must be in the semigroup")
        if len(set(self.elements)) != len(self.elements):
            raise ValueError("requested elements must be distinct")
        declared_order = tuple(
            element for element in self.semigroup.elements if element in self.elements
        )
        if self.elements != declared_order:
            raise ValueError("requested elements must use declared semigroup order")
        return self


class PrincipalIdealsResult(StrictModel):
    """The principal ideals of the requested elements.

    The principal two-sided ideal of ``a`` is ``S^1 a S^1``.
    """

    semigroup: FiniteSemigroup
    elements: tuple[str, ...]
    ideals: tuple[tuple[str, ...], ...]

    @model_validator(mode="after")
    def bind_ideals(self) -> Self:
        from jacobian.math.finite_semigroups._operations import _principal_ideals

        ideals = _principal_ideals(
            self.semigroup.elements,
            self.semigroup.multiplication,
            self.elements,
        )
        if self.ideals != ideals:
            raise ValueError(
                "ideals must be the exact principal ideals of the elements"
            )
        return self
