"""Exact bounded finite semigroup operations."""

from jacobian.math.finite_semigroups._models import (
    ElementPowerRequest,
    ElementPowerResult,
    GeneratedSubsemigroupRequest,
    GeneratedSubsemigroupResult,
    IdempotentsRequest,
    IdempotentsResult,
    PowerProfileRequest,
    PowerProfileResult,
    PrincipalIdealsRequest,
    PrincipalIdealsResult,
)


def _element_power(
    elements: tuple[str, ...],
    multiplication: tuple[tuple[str, ...], ...],
    element: str,
    exponent: int,
) -> str:
    """Compute ``element^exponent`` using its bounded eventual period.

    ``exponent`` must be at least 1; the semigroup may have no identity, so
    ``a^0`` is undefined and rejected at the request boundary.
    """

    powers, index, period, _, _ = _power_profile_data(elements, multiplication, element)
    if exponent < index:
        return powers[exponent - 1]
    return powers[index - 1 + (exponent - index) % period]


def _idempotents(
    elements: tuple[str, ...],
    multiplication: tuple[tuple[str, ...], ...],
) -> tuple[str, ...]:
    """Return every element ``e`` with ``e*e = e`` in declared order."""

    idx = {label: i for i, label in enumerate(elements)}
    return tuple(e for e in elements if multiplication[idx[e]][idx[e]] == e)


def _principal_ideals(
    elements: tuple[str, ...],
    multiplication: tuple[tuple[str, ...], ...],
    requested: tuple[str, ...],
) -> tuple[tuple[str, ...], ...]:
    """Return the principal ideal of each requested element.

    The principal two-sided ideal of ``a`` is ``S^1 a S^1``. Ideals are
    returned in declared element order with each ideal's elements in declared
    semigroup order.
    """

    idx = {label: i for i, label in enumerate(elements)}
    n = len(elements)
    ideals: list[tuple[str, ...]] = []
    for element in requested:
        ideal = {element}
        i = idx[element]
        for left in range(n):
            left_product = multiplication[left][i]
            ideal.add(left_product)
            ideal.add(multiplication[i][left])
            for right in range(n):
                ideal.add(multiplication[idx[left_product]][right])
        ideals.append(tuple(e for e in elements if e in ideal))
    return tuple(ideals)


def _power_profile_data(
    elements: tuple[str, ...],
    multiplication: tuple[tuple[str, ...], ...],
    element: str,
) -> tuple[tuple[str, ...], int, int, str, tuple[str, ...]]:
    """Compute ``(powers, index, period, idempotent, cyclic)`` for one element.

    ``powers[i]`` is ``a^(i+1)`` (1-based exponents).  ``index`` is the
    smallest positive exponent whose power first repeats, ``period`` the
    cycle length, and ``idempotent`` the unique idempotent ``a^k`` with
    ``k >= index`` and ``k ≡ 0 (mod period)``.
    """

    idx = {label: i for i, label in enumerate(elements)}
    a = element
    powers: list[str] = [a]
    seen: dict[str, int] = {a: 0}

    current = a
    zero_based_index = 0
    period = 1
    while True:
        next_power = multiplication[idx[current]][idx[a]]
        if next_power in seen:
            zero_based_index = seen[next_power]
            period = len(powers) - zero_based_index
            break
        seen[next_power] = len(powers)
        powers.append(next_power)
        current = next_power

    index = zero_based_index + 1
    k = index + ((-index) % period)
    idempotent = powers[k - 1]
    cyclic = tuple(powers)
    return tuple(powers), index, period, idempotent, cyclic


def compute_power_profile(request: PowerProfileRequest) -> PowerProfileResult:
    """Compute the power profile of one element in a finite semigroup."""

    powers, index, period, idempotent, cyclic = _power_profile_data(
        request.semigroup.elements,
        request.semigroup.multiplication,
        request.element,
    )
    return PowerProfileResult(
        semigroup=request.semigroup,
        element=request.element,
        powers=powers,
        index=index,
        period=period,
        idempotent=idempotent,
        cyclic_subsemigroup=cyclic,
    )


def compute_generated_subsemigroup(
    request: GeneratedSubsemigroupRequest,
) -> GeneratedSubsemigroupResult:
    """Compute the subsemigroup generated by a set of elements."""

    elements = request.semigroup.elements
    mult = request.semigroup.multiplication
    idx = {label: i for i, label in enumerate(elements)}

    generated = set(request.generators)
    changed = True
    while changed:
        changed = False
        current = list(generated)
        for a in current:
            for b in current:
                product = mult[idx[a]][idx[b]]
                if product not in generated:
                    generated.add(product)
                    changed = True

    # Sort by original element ordering
    result_elements = tuple(e for e in elements if e in generated)
    return GeneratedSubsemigroupResult(
        generators=request.generators,
        elements=result_elements,
    )


def compute_element_power(request: ElementPowerRequest) -> ElementPowerResult:
    """Compute ``element^exponent`` in a finite semigroup."""

    power = _element_power(
        request.semigroup.elements,
        request.semigroup.multiplication,
        request.element,
        request.exponent,
    )
    return ElementPowerResult(
        semigroup=request.semigroup,
        element=request.element,
        exponent=request.exponent,
        power=power,
    )


def compute_idempotents(request: IdempotentsRequest) -> IdempotentsResult:
    """Find every idempotent element ``e`` with ``e*e = e``."""

    idempotents = _idempotents(
        request.semigroup.elements, request.semigroup.multiplication
    )
    return IdempotentsResult(
        semigroup=request.semigroup,
        idempotents=idempotents,
    )


def compute_principal_ideals(request: PrincipalIdealsRequest) -> PrincipalIdealsResult:
    """Compute the principal ideal of each requested element."""

    ideals = _principal_ideals(
        request.semigroup.elements,
        request.semigroup.multiplication,
        request.elements,
    )
    return PrincipalIdealsResult(
        semigroup=request.semigroup,
        elements=request.elements,
        ideals=ideals,
    )
