"""Exact bounded finite semigroup operations."""

from jacobian.math.finite_semigroups._models import (
    GeneratedSubsemigroupRequest,
    GeneratedSubsemigroupResult,
    PowerProfileRequest,
    PowerProfileResult,
)


def _power_profile_data(
    elements: tuple[str, ...],
    multiplication: tuple[tuple[str, ...], ...],
    element: str,
) -> tuple[tuple[str, ...], int, int, str, tuple[str, ...]]:
    """Compute ``(powers, index, period, idempotent, cyclic)`` for one element.

    ``powers[i]`` is ``a^(i+1)`` (1-based exponents).  ``index`` is the
    smallest positive exponent whose power first repeats, ``period`` the
    cycle length, and ``idempotent`` the unique idempotent ``a^k`` with
    ``k >= index`` and ``k ≡ 0 (mod period)``.
    """

    idx = {label: i for i, label in enumerate(elements)}
    a = element
    powers: list[str] = [a]
    seen: dict[str, int] = {a: 0}

    current = a
    zero_based_index = 0
    period = 1
    while True:
        next_power = multiplication[idx[current]][idx[a]]
        if next_power in seen:
            zero_based_index = seen[next_power]
            period = len(powers) - zero_based_index
            break
        seen[next_power] = len(powers)
        powers.append(next_power)
        current = next_power

    index = zero_based_index + 1
    k = index + ((-index) % period)
    idempotent = powers[k - 1]
    cyclic = tuple(powers)
    return tuple(powers), index, period, idempotent, cyclic


def compute_power_profile(request: PowerProfileRequest) -> PowerProfileResult:
    """Compute the power profile of one element in a finite semigroup."""

    powers, index, period, idempotent, cyclic = _power_profile_data(
        request.semigroup.elements,
        request.semigroup.multiplication,
        request.element,
    )
    return PowerProfileResult(
        semigroup=request.semigroup,
        element=request.element,
        powers=powers,
        index=index,
        period=period,
        idempotent=idempotent,
        cyclic_subsemigroup=cyclic,
    )


def compute_generated_subsemigroup(
    request: GeneratedSubsemigroupRequest,
) -> GeneratedSubsemigroupResult:
    """Compute the subsemigroup generated by a set of elements."""

    elements = request.semigroup.elements
    mult = request.semigroup.multiplication
    idx = {label: i for i, label in enumerate(elements)}

    generated = set(request.generators)
    changed = True
    while changed:
        changed = False
        current = list(generated)
        for a in current:
            for b in current:
                product = mult[idx[a]][idx[b]]
                if product not in generated:
                    generated.add(product)
                    changed = True

    # Sort by original element ordering
    result_elements = tuple(e for e in elements if e in generated)
    return GeneratedSubsemigroupResult(
        generators=request.generators,
        elements=result_elements,
    )
