"""Finite semigroup operation declarations."""

from collections.abc import Callable
from typing import Any

from jacobian._models import StrictModel
from jacobian.catalog._examples import example
from jacobian.catalog.models import MathTool, OperationExample
from jacobian.math.finite_semigroups._models import (
    GeneratedSubsemigroupRequest,
    GeneratedSubsemigroupResult,
    PowerProfileRequest,
    PowerProfileResult,
)
from jacobian.math.finite_semigroups._operations import (
    compute_generated_subsemigroup,
    compute_power_profile,
)


def _op[
    RequestT: StrictModel,
    ResultT: StrictModel,
](
    operation_id: str,
    title: str,
    description: str,
    request_model: type[RequestT],
    result_model: type[ResultT],
    operation: Callable[[RequestT], ResultT],
    *tags: str,
    examples: tuple[OperationExample, ...] = (),
) -> MathTool[RequestT, ResultT]:
    return MathTool(
        operation_id=operation_id,
        version="1",
        title=title,
        description=description,
        request_type=request_model,
        result_type=result_model,
        run=operation,
        tags=tags,
        examples=examples,
    )


# The cyclic group Z/3Z as a semigroup (which is also a group)
# Elements: 0, 1, 2 with addition mod 3
_SEMIGROUP = {
    "elements": ["0", "1", "2"],
    "multiplication": [
        ["0", "1", "2"],
        ["1", "2", "0"],
        ["2", "0", "1"],
    ],
}


TOOLS: tuple[MathTool[Any, Any], ...] = (
    _op(
        "semigroup.element.power_profile.compute",
        "Compute the power profile of a semigroup element",
        "Compute the sequence a, a^2, a^3, ... until the first repeat, "
        "determining the one-based index, period, idempotent limit, and "
        "complete cyclic subsemigroup of one element in a finite semigroup.",
        PowerProfileRequest,
        PowerProfileResult,
        compute_power_profile,
        "algebra",
        "semigroup",
        "exact",
        examples=(
            example(
                "cyclic_group_z3",
                "Compute the power profile of element 1 in Z/3Z; "
                "the semigroup must be associative.",
                {
                    "semigroup": _SEMIGROUP,
                    "element": "1",
                },
            ),
        ),
    ),
    _op(
        "semigroup.generated_subsemigroup.compute",
        "Compute the subsemigroup generated by a set of elements",
        "Compute the closure of a set of generators under the semigroup "
        "multiplication, returning all elements in the generated "
        "subsemigroup.",
        GeneratedSubsemigroupRequest,
        GeneratedSubsemigroupResult,
        compute_generated_subsemigroup,
        "algebra",
        "semigroup",
        "exact",
        examples=(
            example(
                "generate_from_1_in_z3",
                "Compute the subsemigroup generated by {1} in Z/3Z; "
                "generators must be in the semigroup.",
                {
                    "semigroup": _SEMIGROUP,
                    "generators": ["1"],
                },
            ),
        ),
    ),
)

__all__ = ["TOOLS"]
