"""Domain functions for finitely generated abelian group operations."""

from __future__ import annotations

from math import gcd, lcm

from jacobian.math.finite_abelian_groups_v2._models import (
    ElementEqualRequest,
    ElementEqualResult,
    ElementOrderRequest,
    ElementOrderResult,
    ElementReduceRequest,
    ElementReduceResult,
    PresentationNormalizeResult,
    QuotientRequest,
    QuotientResult,
    SubgroupGeneratedRequest,
    SubgroupGeneratedResult,
)


def compute_presentation_normalize(
    invariant_factors: tuple[int, ...],
) -> PresentationNormalizeResult:
    from sympy import Matrix, diag
    from sympy.matrices.normalforms import smith_normal_form

    m = Matrix(diag(*invariant_factors))
    smith = smith_normal_form(m, domain=None)
    factors = tuple(int(smith[i, i]) for i in range(min(smith.rows, smith.cols)))

    cleaned: list[int] = []
    for f in factors:
        if f > 1:
            cleaned.append(f)

    order = 1
    for f in cleaned:
        order *= f
    if not cleaned:
        order = 1

    return PresentationNormalizeResult(
        invariant_factors=tuple(cleaned),
        order=order,
        rank=0,
    )


def compute_element_reduce(request: ElementReduceRequest) -> ElementReduceResult:
    reduced = tuple(
        c % d
        for c, d in zip(request.coordinates, request.invariant_factors, strict=True)
    )
    return ElementReduceResult(reduced=reduced)


def compute_element_equal(request: ElementEqualRequest) -> ElementEqualResult:
    reduced_a = tuple(
        c % d
        for c, d in zip(request.coordinates_a, request.invariant_factors, strict=True)
    )
    reduced_b = tuple(
        c % d
        for c, d in zip(request.coordinates_b, request.invariant_factors, strict=True)
    )
    return ElementEqualResult(equal=reduced_a == reduced_b)


def compute_element_order(request: ElementOrderRequest) -> ElementOrderResult:
    reduced = [
        c % d
        for c, d in zip(request.coordinates, request.invariant_factors, strict=True)
    ]
    order = 1
    for coord, factor in zip(reduced, request.invariant_factors, strict=True):
        if coord == 0:
            continue
        elem_order = factor // gcd(coord, factor)
        order = lcm(order, elem_order)

    return ElementOrderResult(order=order)


def _smith_diagonal(augmented_rows: list[list[int]]) -> list[int]:
    """Compute the diagonal entries of the Smith normal form of an integer matrix.

    Uses SymPy's exact integer Smith normal form; fails closed on import errors
    rather than fabricating invariants from the untransformed matrix.
    """
    from sympy import Matrix
    from sympy.matrices.normalforms import smith_normal_form

    smith = smith_normal_form(Matrix(augmented_rows), domain=None)
    return [abs(int(smith[i, i])) for i in range(min(smith.rows, smith.cols))]


def compute_subgroup_generated(
    request: SubgroupGeneratedRequest,
) -> SubgroupGeneratedResult:
    """Compute [G : H] via the Smith normal form of the presentation matrix.

    G = Z/d_1 x ... x Z/d_n is presented by the diagonal matrix D = diag(d_1,
    ..., d_n).  The subgroup H generated by g_1, ..., g_m is presented by the
    augmented matrix [D | g_1^T ... g_m^T].  The index [G : H] equals |G / H|,
    the product of the diagonal entries > 1 of the SNF of the augmented matrix.
    Both |G| and the SNF computation are bounded by the request validator
    (|G| <= 4096), so this is a single bounded algebraic operation rather than
    an enumeration.
    """
    factors = request.invariant_factors
    n = len(factors)

    rows = [[0] * n for _ in range(n)]
    for i in range(n):
        rows[i][i] = factors[i]
    for gen in request.generators:
        for i in range(n):
            rows[i].append(gen[i])

    diagonal = _smith_diagonal(rows)

    index = 1
    for d in diagonal:
        if d > 1:
            index *= d

    return SubgroupGeneratedResult(index=index)


def compute_quotient(request: QuotientRequest) -> QuotientResult:
    """Compute G/H via Smith normal form of the presentation matrix.

    G = Z/d_1 x ... x Z/d_n, H = <g_1, ..., g_m>.
    The quotient G/H has presentation matrix [diag(d_1,...,d_n) | g_1 ... g_m]
    reduced to Smith normal form.
    """
    factors = request.invariant_factors
    n = len(factors)

    rows = [[0] * n for _ in range(n)]
    for i in range(n):
        rows[i][i] = factors[i]
    for gen in request.subgroup_generators:
        for i in range(n):
            rows[i].append(gen[i])

    diagonal = _smith_diagonal(rows)

    factors_out = []
    for d in diagonal:
        if d > 1:
            factors_out.append(d)

    order = 1
    for f in factors_out:
        order *= f
    if not factors_out:
        order = 1

    return QuotientResult(
        quotient_invariant_factors=tuple(factors_out),
        quotient_order=order,
    )
