"""Formal concept analysis operation declarations."""

from collections.abc import Callable
from typing import Any

from jacobian._models import StrictModel
from jacobian.catalog._examples import example
from jacobian.catalog.models import MathTool, OperationExample
from jacobian.math.formal_concept_analysis._models import (
    AttributeSubsetRequest,
    ClosureResult,
    ConceptLatticeResult,
    ConceptResult,
    DerivationResult,
    EnumerateConceptsRequest,
    EnumerateConceptsResult,
    ObjectSubsetRequest,
)
from jacobian.math.formal_concept_analysis._operations import (
    compute_attribute_derivation,
    compute_concept_from_attributes,
    compute_concept_from_objects,
    compute_concept_lattice,
    compute_enumerate_concepts,
    compute_object_closure,
    compute_object_derivation,
)


def _op[
    RequestT: StrictModel,
    ResultT: StrictModel,
](
    operation_id: str,
    title: str,
    description: str,
    request_model: type[RequestT],
    result_model: type[ResultT],
    operation: Callable[[RequestT], ResultT],
    *tags: str,
    examples: tuple[OperationExample, ...] = (),
    version: str = "1",
) -> MathTool[RequestT, ResultT]:
    return MathTool(
        operation_id=operation_id,
        version=version,
        title=title,
        description=description,
        request_type=request_model,
        result_type=result_model,
        run=operation,
        tags=tags,
        examples=examples,
    )


# A simple 2x2 context: objects {o0, o1}, attributes {a0, a1}
# o0 has a0; o1 has a1.
_CONTEXT = {
    "objects": ["o0", "o1"],
    "attributes": ["a0", "a1"],
    "incidence": [[0, 0], [1, 1]],
}


FORMAL_CONCEPT_ANALYSIS_OPERATIONS: tuple[MathTool[Any, Any], ...] = (
    _op(
        "formal_context.objects.derivation.compute",
        "Compute A' = {m : every g in A has m}",
        "Return the exact derived attribute set for an object subset. Under "
        "standard FCA semantics, the derivation of the empty object set is "
        "every attribute.",
        ObjectSubsetRequest,
        DerivationResult,
        compute_object_derivation,
        "formal-concept-analysis",
        "derivation",
        "exact",
        examples=(
            example(
                "empty_object_set",
                "Derivation of the empty object set is every attribute.",
                {"context": _CONTEXT, "subset": []},
            ),
        ),
    ),
    _op(
        "formal_context.attributes.derivation.compute",
        "Compute B' = {g : every m in B is possessed by g}",
        "Return the exact derived object set for an attribute subset. Under "
        "standard FCA semantics, the derivation of the empty attribute set is "
        "every object.",
        AttributeSubsetRequest,
        DerivationResult,
        compute_attribute_derivation,
        "formal-concept-analysis",
        "derivation",
        "exact",
        examples=(
            example(
                "empty_attribute_set",
                "Derivation of the empty attribute set is every object.",
                {"context": _CONTEXT, "subset": []},
            ),
        ),
    ),
    _op(
        "formal_context.objects.closure.compute",
        "Compute A'' = (A')' with added objects and closed status",
        "Return the object closure A'' with the derived attributes A', added "
        "objects A''\\A, and whether A is already closed.",
        ObjectSubsetRequest,
        ClosureResult,
        compute_object_closure,
        "formal-concept-analysis",
        "closure",
        "exact",
        examples=(
            example(
                "empty_object_closure",
                "Closure of the empty object set.",
                {"context": _CONTEXT, "subset": []},
            ),
        ),
    ),
    _op(
        "formal_context.concept.from_objects.compute",
        "Construct the concept (A'', A') from an object subset",
        "Return the unique concept generated by an object subset: (A'', A').",
        ObjectSubsetRequest,
        ConceptResult,
        compute_concept_from_objects,
        "formal-concept-analysis",
        "concept",
        "exact",
        examples=(
            example(
                "concept_from_o0",
                "Concept from object o0.",
                {"context": _CONTEXT, "subset": [0]},
            ),
        ),
    ),
    _op(
        "formal_context.concept.from_attributes.compute",
        "Construct the concept (B', B'') from an attribute subset",
        "Return the unique concept generated by an attribute subset: (B', B'').",
        AttributeSubsetRequest,
        ConceptResult,
        compute_concept_from_attributes,
        "formal-concept-analysis",
        "concept",
        "exact",
        examples=(
            example(
                "concept_from_a0",
                "Concept from attribute a0.",
                {"context": _CONTEXT, "subset": [0]},
            ),
        ),
    ),
    _op(
        "formal_context.concepts.enumerate.compute",
        "Enumerate every formal concept exactly once",
        "Return the complete concept family of closed attribute intents "
        "using Ganter's NextClosure algorithm over the declared attribute "
        "order. The family, not the enumeration order, is mathematical.",
        EnumerateConceptsRequest,
        EnumerateConceptsResult,
        compute_enumerate_concepts,
        "formal-concept-analysis",
        "enumeration",
        "exact",
        examples=(
            example(
                "enumerate_concepts",
                "Enumerate all concepts of a 2x2 context.",
                {"context": _CONTEXT},
            ),
        ),
    ),
    _op(
        "formal_context.concept_lattice.compute",
        "Compute the concept lattice",
        "Return the complete concepts, partial order by extent inclusion, "
        "cover relation/Hasse diagram, and top and bottom concepts.",
        EnumerateConceptsRequest,
        ConceptLatticeResult,
        compute_concept_lattice,
        "formal-concept-analysis",
        "lattice",
        "exact",
        examples=(
            example(
                "concept_lattice",
                "Concept lattice of a 2x2 context.",
                {"context": _CONTEXT},
            ),
        ),
    ),
)

TOOLS = FORMAL_CONCEPT_ANALYSIS_OPERATIONS

__all__ = ["TOOLS"]
