"""Domain functions for commutative algebra operations."""

from __future__ import annotations

import sympy

from jacobian.math.commutative_algebra_ops._models import (
    IdealQuotientRequest,
    IdealQuotientResult,
    IdealRadicalMembershipRequest,
    IdealRadicalMembershipResult,
    IdealRadicalRequest,
    IdealRadicalResult,
)


def _parse_generators(
    generators: tuple[str, ...], variables: tuple[str, ...]
) -> list[sympy.Expr]:
    """Parse generator strings into SymPy expressions over the given variables."""
    var_symbols = tuple(sympy.Symbol(v) for v in variables)
    var_map = dict(zip(variables, var_symbols, strict=True))
    return [sympy.sympify(gen, locals=var_map) for gen in generators]


def _groebner(
    generators: list[sympy.Expr], var_symbols: tuple[sympy.Symbol, ...]
) -> sympy.GroebnerBasis:
    """Compute a Groebner basis, with grevlex ordering for efficiency."""
    return sympy.groebner(generators, *var_symbols, order="grevlex")


def _square_free_part(
    expr: sympy.Expr, var_symbols: tuple[sympy.Symbol, ...]
) -> sympy.Expr:
    """Compute the square-free part of a polynomial.

    Divides out the greatest common divisor of the expression with each of
    its partial derivatives, yielding a square-free polynomial with the same
    variety as the original.
    """
    if expr == 0:
        return expr
    result = expr
    for v in var_symbols:
        d = sympy.diff(result, v)
        if d != 0:
            g = sympy.gcd(result, d)
            if g != 1 and g != 0:
                result = sympy.cancel(result / g)
    return sympy.expand(result)


def compute_ideal_radical(request: IdealRadicalRequest) -> IdealRadicalResult:
    """Compute the radical of an ideal.

    For a polynomial ideal I = <f1, ..., fn>, the radical sqrt(I) is the smallest
    radical ideal containing I. We compute it by:
      1. Computing the Groebner basis G of I.
      2. Taking the square-free part of each basis element.

    The radical of I is generated by the square-free parts of a Groebner basis
    of I. This is correct because the radical of a principal ideal <g> is
    <sqfree(g)>, and the Groebner basis reduces the general case to principal
    generators.
    """
    var_symbols = tuple(sympy.Symbol(v) for v in request.variables)
    generators = _parse_generators(request.generators, request.variables)

    basis = _groebner(generators, var_symbols)
    radical_gens: list[str] = []
    for poly in basis:
        sqfree = _square_free_part(poly, var_symbols)
        if sqfree != 0:
            radical_gens.append(str(sympy.expand(sqfree)))

    if not radical_gens:
        radical_gens = ["0"]

    return IdealRadicalResult(generators=tuple(radical_gens))


def compute_ideal_radical_membership(
    request: IdealRadicalMembershipRequest,
) -> IdealRadicalMembershipResult:
    """Check if a polynomial f is in the radical of an ideal I.

    Uses the Rabinowitsch trick: f in sqrt(I) iff 1 in <I, 1 - t*f> for a new
    variable t. Equivalently, the ideal <I, 1 - t*f> is trivial (contains 1).
    """
    var_symbols = tuple(sympy.Symbol(v) for v in request.variables)
    ideal_gens = _parse_generators(request.generators, request.variables)
    var_map = dict(zip(request.variables, var_symbols, strict=True))
    f = sympy.sympify(request.polynomial, locals=var_map)

    t = sympy.Symbol("_t")
    augmented = [*ideal_gens, 1 - t * f]
    all_vars = (*var_symbols, t)

    basis = _groebner(augmented, all_vars)

    in_radical = len(basis) == 1 and basis[0] == 1

    return IdealRadicalMembershipResult(in_radical=in_radical)


def compute_ideal_quotient(request: IdealQuotientRequest) -> IdealQuotientResult:
    """Compute the ideal quotient (I : J) = {f : f*J subseteq I}.

    For each generator g of J, compute the colon ideal (I : g) using the
    elimination approach:
      1. Introduce a new variable t.
      2. Compute I intersect <g> as the elimination ideal of <t*I, (1-t)*g>.
      3. (I : g) = (I intersect <g>) / g.

    The final quotient (I : J) is the intersection of all (I : g) for g in J.
    """
    var_symbols = tuple(sympy.Symbol(v) for v in request.variables)
    gens_a = _parse_generators(request.generators_a, request.variables)
    gens_b = _parse_generators(request.generators_b, request.variables)

    t = sympy.Symbol("_t")
    all_vars = (*var_symbols, t)

    def _eliminate_t(basis: sympy.GroebnerBasis) -> list[sympy.Expr]:
        """Extract generators not involving t from a basis."""
        return [p for p in basis if not p.has(t)]

    def _colon_single(g: sympy.Expr) -> list[sympy.Expr]:
        """Compute (I : g) via the elimination approach."""
        augmented = [t * f for f in gens_a] + [(1 - t) * g]
        basis = _groebner(augmented, all_vars)
        eliminated = _eliminate_t(basis)
        return [sympy.expand(sympy.cancel(p / g)) for p in eliminated]

    def _intersect(
        gens_i: list[sympy.Expr], gens_j: list[sympy.Expr]
    ) -> list[sympy.Expr]:
        """Compute I intersect J via elimination: <t*I, (1-t)*J> intersect k[vars]."""
        augmented = [t * f for f in gens_i] + [(1 - t) * f for f in gens_j]
        basis = _groebner(augmented, all_vars)
        return [sympy.expand(p) for p in _eliminate_t(basis)]

    # Compute (I : J) = intersection of (I : g) for each g in J
    colon_ideals = [_colon_single(g) for g in gens_b]

    if not colon_ideals:
        return IdealQuotientResult(generators=("0",))

    result = colon_ideals[0]
    for colon in colon_ideals[1:]:
        result = _intersect(result, colon)

    quotient_gens = [str(p) for p in result if p != 0]
    if not quotient_gens:
        quotient_gens = ["0"]

    return IdealQuotientResult(generators=tuple(quotient_gens))
