"""Tests for linear code structural operations."""

import pytest
from pydantic import ValidationError

from jacobian.math.code_linear._models import (
    CodeEqualRequest,
    CodewordCheckRequest,
    GeneratorMatrixRequest,
    MacWilliamsRequest,
    ParityCheckRequest,
    PunctureRequest,
    ShortenRequest,
    SyndromeRequest,
)
from jacobian.math.code_linear._operations import (
    compute_code_equal,
    compute_codeword_check,
    compute_dual_code,
    compute_from_generator,
    compute_macwilliams_transform,
    compute_parity_check,
    compute_puncture,
    compute_shorten,
    compute_syndrome,
)
from jacobian.math.code_linear._tools import TOOLS


def test_catalog_contains_only_audited_operations() -> None:
    expected = {
        "code.linear.codeword.check",
        "code.linear.dual.compute",
        "code.linear.equal.decide",
        "code.linear.from_generator.compute",
        "code.linear.macwilliams_transform.compute",
        "code.linear.parity_check.compute",
        "code.linear.puncture.compute",
        "code.linear.shorten.compute",
        "code.linear.syndrome.compute",
    }
    assert {tool.operation_id for tool in TOOLS} == expected


def test_from_generator_canonicalizes_dependent_rows() -> None:
    request = GeneratorMatrixRequest(field_order=2, generator_matrix=((1, 1), (1, 1)))
    result = compute_from_generator(request)
    assert result.dimension == 1
    assert result.length == 2
    assert result.cardinality == 2
    assert result.canonical_generator == ((1, 1),)


def test_dual_of_repetition_is_parity_check() -> None:
    request = GeneratorMatrixRequest(field_order=2, generator_matrix=((1, 1),))
    result = compute_dual_code(request)
    assert result.dimension == 1
    assert result.dual_dimension == 1
    assert result.length == 2
    assert len(result.dual_generator) == 1


def test_parity_check_matches_dual() -> None:
    request = ParityCheckRequest(field_order=2, generator_matrix=((1, 1),))
    result = compute_parity_check(request)
    assert result.dimension == 1
    assert result.rank_h == 1
    assert result.length == 2
    assert len(result.parity_check) == 1


def test_codeword_check_member() -> None:
    request = CodewordCheckRequest(
        field_order=2, generator_matrix=((1, 1),), word=(1, 1)
    )
    result = compute_codeword_check(request)
    assert result.is_member is True
    assert result.hamming_weight == 2


def test_codeword_check_nonmember() -> None:
    request = CodewordCheckRequest(
        field_order=2, generator_matrix=((1, 1),), word=(1, 0)
    )
    result = compute_codeword_check(request)
    assert result.is_member is False
    assert result.hamming_weight == 1


def test_syndrome_zero_for_codeword() -> None:
    request = SyndromeRequest(field_order=2, parity_check_matrix=((1, 1),), word=(1, 1))
    result = compute_syndrome(request)
    assert result.syndrome == (0,)
    assert result.is_member is True


def test_syndrome_nonzero_for_noncodeword() -> None:
    request = SyndromeRequest(field_order=2, parity_check_matrix=((1, 1),), word=(1, 0))
    result = compute_syndrome(request)
    assert result.syndrome == (1,)
    assert result.is_member is False


def test_code_equal_same_matrices() -> None:
    request = CodeEqualRequest(
        field_order=2,
        generator_matrix_a=((1, 1),),
        generator_matrix_b=((1, 1),),
    )
    result = compute_code_equal(request)
    assert result.equal is True
    assert result.witness_word is None


def test_code_equal_different_codes() -> None:
    request = CodeEqualRequest(
        field_order=2,
        generator_matrix_a=((1, 0),),
        generator_matrix_b=((0, 1),),
    )
    result = compute_code_equal(request)
    assert result.equal is False
    assert result.witness_word is not None


def test_macwilliams_self_dual_repetition_code() -> None:
    request = MacWilliamsRequest(
        field_order=2, code_cardinality=2, length=2, weights=(1, 0, 1)
    )
    result = compute_macwilliams_transform(request)
    assert result.dual_weights == (1, 0, 1)


def test_puncture_reduces_length() -> None:
    request = PunctureRequest(field_order=2, generator_matrix=((1, 1),), coordinate=0)
    result = compute_puncture(request)
    assert result.length == 1
    assert result.dimension == 1


def test_shorten_reduces_dimension_and_length() -> None:
    # Shortening the length-3 binary repetition code at coordinate 0
    # keeps codewords with c[0]=0 (only the zero word), so dimension drops to 0.
    request = ShortenRequest(field_order=2, generator_matrix=((1, 1, 1),), coordinate=0)
    result = compute_shorten(request)
    assert result.length == 2
    assert result.dimension == 0


def test_shorten_2d_code() -> None:
    # Code generated by [[1,1,0],[1,0,1]] over F_2.
    # Codewords: 000, 110, 101, 011.
    # Shortening at coordinate 0: keep codewords with c[0]=0: {000, 011}.
    # Delete coordinate 0: {00, 11} -> dimension 1, length 2.
    request = ShortenRequest(
        field_order=2, generator_matrix=((1, 1, 0), (1, 0, 1)), coordinate=0
    )
    result = compute_shorten(request)
    assert result.length == 2
    assert result.dimension == 1


def test_macwilliams_ternary() -> None:
    # Ternary repetition code: C = {00, 11, 22}, q=3, n=2
    # Weight distribution: A_0=1, A_1=0, A_2=2
    # Dual weight distribution should also be (1, 0, 2) since it's self-dual.
    request = MacWilliamsRequest(
        field_order=3,
        code_cardinality=3,
        length=2,
        weights=(1, 0, 2),
    )
    result = compute_macwilliams_transform(request)
    assert result.dual_weights == (1, 0, 2)


def test_request_rejects_nonprime_field() -> None:
    with pytest.raises(ValidationError, match="prime"):
        GeneratorMatrixRequest(field_order=4, generator_matrix=((1,),))


def test_request_rejects_bad_entry() -> None:
    with pytest.raises(ValidationError, match="residues"):
        GeneratorMatrixRequest(field_order=2, generator_matrix=((2,),))


def test_syndrome_request_rejects_bad_word_length() -> None:
    with pytest.raises(ValidationError, match="length"):
        SyndromeRequest(field_order=2, parity_check_matrix=((1, 1),), word=(1,))


def test_codeword_check_request_rejects_bad_word_length() -> None:
    with pytest.raises(ValidationError, match="length"):
        CodewordCheckRequest(field_order=2, generator_matrix=((1, 1),), word=(1,))
