"""Typed wire contracts for finite group-action operations."""

from __future__ import annotations

from typing import Self

from pydantic import Field, model_validator

from jacobian._models import StrictModel

MAX_DOMAIN_SIZE = 50
MAX_GROUP_ORDER = 720
MAX_LABEL_LENGTH = 64
MAX_COLORS = 50
MAX_TERMS = 5000


class FinitePermutationAction(StrictModel):
    """A finite permutation group acting on a labelled set.

    ``domain`` is the tuple of unique string labels for the set ``X`` being
    acted on.  ``generators`` is a tuple of permutations of ``{0, ..., n-1}``
    (each a tuple of length ``n`` where ``permutation[i]`` is the image of
    ``domain[i]``).  The group is generated by the generators under
    composition; the action convention is a left action.
    """

    domain: tuple[str, ...] = Field(min_length=1, max_length=MAX_DOMAIN_SIZE)
    generators: tuple[tuple[int, ...], ...] = Field(min_length=1)

    @model_validator(mode="after")
    def require_valid_action(self) -> Self:
        labels = set(self.domain)
        if len(labels) != len(self.domain):
            raise ValueError("domain labels must be distinct")
        for label in self.domain:
            if len(label) > MAX_LABEL_LENGTH:
                raise ValueError("domain label exceeds the bounded length budget")
        n = len(self.domain)
        for perm in self.generators:
            if len(perm) != n:
                raise ValueError("every generator must be a permutation of the domain")
            if sorted(perm) != list(range(n)):
                raise ValueError(
                    "every generator must be a total permutation of the domain"
                )
        return self


class _ActionRequest(StrictModel):
    """Shared request shape: one finite permutation action."""

    action: FinitePermutationAction


# ---------------------------------------------------------------------------
# group_action.element_cycles.compute
# ---------------------------------------------------------------------------


class ElementCyclesRequest(_ActionRequest):
    """Request the cycle decomposition of one group element.

    ``element`` is the index (0-based) into the enumerated group order of the
    action; the identity element is always at index 0.
    """

    element: int = Field(ge=0)


class ElementCyclesResult(StrictModel):
    """Cycle decomposition of one group element acting on the domain.

    Each ``cycle`` is a tuple of 0-based position indices in the domain.  The
    canonical representative starts with the smallest index and cycles are
    ordered by their smallest element.  ``cycle_lengths`` is the sorted list
    of cycle lengths; ``cycle_type`` is the integer partition of ``|X|`` given
    by the cycle lengths in non-increasing order.  ``fixed_points`` lists the
    domain indices fixed by the element.
    """

    action: FinitePermutationAction
    element: int
    permutation: tuple[int, ...]
    cycles: tuple[tuple[int, ...], ...]
    cycle_lengths: tuple[int, ...]
    cycle_type: tuple[int, ...]
    fixed_points: tuple[int, ...]
    fixed_point_count: int
    support: tuple[int, ...]

    @model_validator(mode="after")
    def bind_element_cycles(self) -> Self:
        from jacobian.math.finite_group_actions._operations import _element_cycles_data

        permutation, cycles, lengths, cycle_type, fixed, support = _element_cycles_data(
            self.action, self.element
        )
        if self.permutation != permutation:
            raise ValueError("permutation must be the exact enumerated group element")
        if self.cycles != cycles:
            raise ValueError("cycles must be the exact cycle decomposition")
        if self.cycle_lengths != lengths:
            raise ValueError("cycle_lengths must match the computed cycle lengths")
        if self.cycle_type != cycle_type:
            raise ValueError("cycle_type must be the integer partition of |X|")
        if self.fixed_points != fixed:
            raise ValueError("fixed_points must be the exact fixed-point set")
        if self.fixed_point_count != len(fixed):
            raise ValueError("fixed_point_count must equal len(fixed_points)")
        if self.support != support:
            raise ValueError("support must be the exact support set")
        return self


# ---------------------------------------------------------------------------
# group_action.cycle_index.compute
# ---------------------------------------------------------------------------


class CycleIndexRequest(_ActionRequest):
    """Request the cycle-index polynomial of the action."""


class CycleIndexResult(StrictModel):
    """The cycle-index polynomial Z(G) as sparse coefficient data.

    ``cycle_type -> coefficient`` maps a cycle-type tuple (an integer partition
    of ``|X|`` given by cycle counts) to the number of group elements with
    that cycle type.  ``group_order`` is ``|G|`` and ``degree`` is ``|X|``.
    Each coefficient is exact; the cycle index is ``coeff / group_order``.
    """

    action: FinitePermutationAction
    group_order: int
    degree: int
    cycle_type_counts: tuple[tuple[tuple[int, ...], int], ...]

    @model_validator(mode="after")
    def bind_cycle_index(self) -> Self:
        from jacobian.math.finite_group_actions._operations import _cycle_index_data

        order, degree, counts = _cycle_index_data(self.action)
        if self.group_order != order:
            raise ValueError("group_order must equal the exact |G|")
        if self.degree != degree:
            raise ValueError("degree must equal |X|")
        if self.cycle_type_counts != counts:
            raise ValueError(
                "cycle_type_counts must be the exact cycle-type multiplicity table"
            )
        return self


# ---------------------------------------------------------------------------
# group_action.burnside_count.compute
# ---------------------------------------------------------------------------


class BurnsideCountRequest(_ActionRequest):
    """Request the number of orbits under the action via Burnside's lemma."""


class BurnsideCountResult(StrictModel):
    """The number of point-orbits under the action.

    ``orbit_count`` is the exact integer ``|G\\X| = (1/|G|) sum_g |Fix(g)|``.
    ``fixed_point_contributions`` lists, for each group element, its
    ``|Fix(g)|`` value in enumerated order.  ``group_order`` is ``|G|``.
    """

    action: FinitePermutationAction
    group_order: int
    fixed_point_sum: int
    orbit_count: int
    fixed_point_contributions: tuple[int, ...]

    @model_validator(mode="after")
    def bind_burnside(self) -> Self:
        from jacobian.math.finite_group_actions._operations import _burnside_data

        order, contributions, orbit_count = _burnside_data(self.action)
        if self.group_order != order:
            raise ValueError("group_order must equal the exact |G|")
        if self.fixed_point_contributions != contributions:
            raise ValueError(
                "fixed_point_contributions must be the exact |Fix(g)| table"
            )
        if self.fixed_point_sum != sum(contributions):
            raise ValueError("fixed_point_sum must equal the sum of contributions")
        if self.orbit_count != orbit_count:
            raise ValueError("orbit_count must equal the exact Burnside orbit count")
        return self


# ---------------------------------------------------------------------------
# group_action.polya_inventory.compute
# ---------------------------------------------------------------------------


class PolyaInventoryRequest(_ActionRequest):
    """Request the Pólya enumeration inventory polynomial.

    ``colors`` is the number of colours ``k``.  The inventory polynomial counts
    colouring orbits of ``X`` by colour multiplicity.  Its monomials are
    ``k``-tuples ``(e_1, ..., e_k)`` summing to ``|X|`` and its coefficients
    count orbits of colourings with exactly ``e_c`` points of colour ``c``.
    """

    colors: int = Field(ge=1, le=MAX_COLORS)


class PolyaInventoryResult(StrictModel):
    """The Pólya enumeration inventory polynomial as sparse data.

    ``terms`` maps each monomial exponent tuple (a ``k``-tuple of non-negative
    integers summing to ``degree``) to its integer coefficient.  ``colors`` is
    the number of colours and ``degree`` is ``|X|``.  The coefficient sum is
    ``k^|X| / |G| * |G| = k^|X|`` only when the action is trivial; in general
    the coefficients are the Pólya inventory coefficients.
    """

    action: FinitePermutationAction
    colors: int = Field(ge=1, le=MAX_COLORS)
    degree: int
    terms: tuple[tuple[tuple[int, ...], int], ...]

    @model_validator(mode="after")
    def bind_polya(self) -> Self:
        from jacobian.math.finite_group_actions._operations import _polya_inventory_data

        degree, terms = _polya_inventory_data(self.action, self.colors)
        if self.degree != degree:
            raise ValueError("degree must equal |X|")
        if self.terms != terms:
            raise ValueError("terms must be the exact Pólya inventory polynomial")
        return self
