"""Exact bounded finite group-action operations."""

from __future__ import annotations

from jacobian.math.finite_group_actions._models import (
    BurnsideCountRequest,
    BurnsideCountResult,
    CycleIndexRequest,
    CycleIndexResult,
    ElementCyclesRequest,
    ElementCyclesResult,
    FinitePermutationAction,
    PolyaInventoryRequest,
    PolyaInventoryResult,
)

MAX_GROUP_ORDER = 720

CycleTypeCount = tuple[tuple[int, ...], int]


def _compose(a: tuple[int, ...], b: tuple[int, ...]) -> tuple[int, ...]:
    """Return ``a ∘ b`` so that ``(a ∘ b)[i] = a[b[i]]`` (left action)."""
    return tuple(a[b[i]] for i in range(len(a)))


def _identity(n: int) -> tuple[int, ...]:
    return tuple(range(n))


def _enumerate_group(
    action: FinitePermutationAction,
) -> tuple[tuple[int, ...], ...]:
    """Enumerate the group generated by the action's generators under composition.

    The identity element is always at index 0.  The remaining elements are
    ordered by first discovery in a breadth-first closure.  The group order
    must not exceed the bounded maximum.
    """

    n = len(action.domain)
    identity = _identity(n)
    seen: dict[tuple[int, ...], int] = {identity: 0}
    elements: list[tuple[int, ...]] = [identity]
    frontier: list[tuple[int, ...]] = [identity]
    while frontier:
        new_frontier: list[tuple[int, ...]] = []
        for elem in frontier:
            for gen in action.generators:
                composed = _compose(gen, elem)
                if composed not in seen:
                    seen[composed] = len(elements)
                    elements.append(composed)
                    new_frontier.append(composed)
        frontier = new_frontier
    if len(elements) > MAX_GROUP_ORDER:
        raise ValueError(
            f"group order {len(elements)} exceeds the bounded maximum {MAX_GROUP_ORDER}"
        )
    return tuple(elements)


def _cycle_decomposition(
    perm: tuple[int, ...],
) -> tuple[
    tuple[tuple[int, ...], ...], tuple[int, ...], tuple[int, ...], tuple[int, ...]
]:
    """Return ``(cycles, lengths, cycle_type, fixed)`` for one permutation.

    Cycles use the canonical representative starting with the smallest index
    and are ordered by their smallest element.  Fixed points are cycles of
    length 1.  ``cycle_type`` is the integer partition of ``n`` given by cycle
    lengths in non-increasing order.  ``fixed`` lists fixed-point indices in
    increasing order.
    """
    n = len(perm)
    visited = [False] * n
    cycles: list[tuple[int, ...]] = []
    for start in range(n):
        if visited[start]:
            continue
        cycle: list[int] = []
        current = start
        while not visited[current]:
            visited[current] = True
            cycle.append(current)
            current = perm[current]
        cycles.append(tuple(cycle))
    # Canonical: order cycles by smallest element, rotate each to start there.
    cycles.sort(key=lambda c: min(c))
    lengths = tuple(sorted((len(c) for c in cycles), reverse=True))
    fixed = tuple(i for i in range(n) if perm[i] == i)
    return tuple(cycles), lengths, lengths, fixed


def _support(perm: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(i for i in range(len(perm)) if perm[i] != i)


def _element_cycles_data(
    action: FinitePermutationAction,
    element: int,
) -> tuple[
    tuple[int, ...],
    tuple[tuple[int, ...], ...],
    tuple[int, ...],
    tuple[int, ...],
    tuple[int, ...],
    tuple[int, ...],
]:
    group = _enumerate_group(action)
    if element < 0 or element >= len(group):
        raise ValueError("element index is out of range for the group order")
    perm = group[element]
    cycles, lengths, cycle_type, fixed = _cycle_decomposition(perm)
    support = _support(perm)
    return perm, cycles, lengths, cycle_type, fixed, support


def _cycle_type_counts(
    action: FinitePermutationAction,
) -> tuple[CycleTypeCount, ...]:
    """Return the cycle-type multiplicity table as a sorted tuple of (type, count)."""
    group = _enumerate_group(action)
    counts: dict[tuple[int, ...], int] = {}
    for perm in group:
        _, _, cycle_type, _ = _cycle_decomposition(perm)
        counts[cycle_type] = counts.get(cycle_type, 0) + 1
    return tuple(sorted(counts.items()))


def _cycle_index_data(
    action: FinitePermutationAction,
) -> tuple[int, int, tuple[CycleTypeCount, ...]]:
    """Return ``(group_order, degree, cycle_type_counts)``."""
    group = _enumerate_group(action)
    degree = len(action.domain)
    counts = _cycle_type_counts(action)
    return len(group), degree, counts


def _burnside_data(
    action: FinitePermutationAction,
) -> tuple[int, tuple[int, ...], int]:
    """Return ``(group_order, fixed_point_contributions, orbit_count)``."""
    group = _enumerate_group(action)
    contributions: list[int] = []
    for perm in group:
        _, _, _, fixed = _cycle_decomposition(perm)
        contributions.append(len(fixed))
    group_order = len(group)
    total = sum(contributions)
    if total % group_order != 0:
        raise ValueError("Burnside orbit count is not an integer")
    orbit_count = total // group_order
    return group_order, tuple(contributions), orbit_count


def _polya_inventory_data(
    action: FinitePermutationAction,
    colors: int,
) -> tuple[int, tuple[tuple[tuple[int, ...], int], ...]]:
    """Return ``(degree, terms)`` for the Pólya inventory polynomial.

    For a colouring ``X -> {1..k}``, each group element ``g`` contributes
    ``prod_i a_i^{c_i(g)}`` to the cycle index.  Substituting
    ``a_i <- sum_c y_c^i`` and expanding gives the inventory polynomial whose
    monomials are exponent tuples of length ``colors`` and coefficients count
    colouring orbits by colour multiplicity.
    """
    group = _enumerate_group(action)
    degree = len(action.domain)
    if colors < 1:
        raise ValueError("colors must be at least 1")
    orbit_count: dict[tuple[int, ...], int] = {}
    for perm in group:
        cycles, _, _, _ = _cycle_decomposition(perm)
        # Build the monomial exponent-tuple contribution of this element.
        # cycle of length i contributes sum_c y_c^i, so for each monomial we
        # choose one term per cycle.  Accumulate the product over cycles.
        # Each cycle of length L contributes (y_c)^L for some colour c.
        # We represent each cycle's choice as an exponent vector of length
        # colors, where entry c is L if that colour is chosen.
        cycle_choices: list[list[tuple[int, ...]]] = []
        for cycle in cycles:
            length = len(cycle)
            choices = []
            for c in range(colors):
                exponents = [0] * colors
                exponents[c] = length
                choices.append(tuple(exponents))
            cycle_choices.append(choices)
        # Cartesian product over cycles
        from itertools import product as _product

        for assignment in _product(*cycle_choices):
            monomial = tuple(
                sum(assignment[j][c] for j in range(len(assignment)))
                for c in range(colors)
            )
            orbit_count[monomial] = orbit_count.get(monomial, 0) + 1
    group_order = len(group)
    terms: list[tuple[tuple[int, ...], int]] = []
    for monomial, count in orbit_count.items():
        if count % group_order != 0:
            raise ValueError("Pólya inventory coefficient is not an integer")
        terms.append((monomial, count // group_order))
    terms.sort(key=lambda t: t[0])
    return degree, tuple(terms)


def compute_element_cycles(
    request: ElementCyclesRequest,
) -> ElementCyclesResult:
    """Compute the cycle decomposition of one group element."""
    perm, cycles, lengths, cycle_type, fixed, support = _element_cycles_data(
        request.action, request.element
    )
    return ElementCyclesResult(
        action=request.action,
        element=request.element,
        permutation=perm,
        cycles=cycles,
        cycle_lengths=lengths,
        cycle_type=cycle_type,
        fixed_points=fixed,
        fixed_point_count=len(fixed),
        support=support,
    )


def compute_cycle_index(request: CycleIndexRequest) -> CycleIndexResult:
    """Compute the cycle-index polynomial of the action."""
    group_order, degree, counts = _cycle_index_data(request.action)
    return CycleIndexResult(
        action=request.action,
        group_order=group_order,
        degree=degree,
        cycle_type_counts=counts,
    )


def compute_burnside_count(request: BurnsideCountRequest) -> BurnsideCountResult:
    """Compute the number of orbits under the action via Burnside's lemma."""
    group_order, contributions, orbit_count = _burnside_data(request.action)
    return BurnsideCountResult(
        action=request.action,
        group_order=group_order,
        fixed_point_sum=sum(contributions),
        orbit_count=orbit_count,
        fixed_point_contributions=contributions,
    )


def compute_polya_inventory(request: PolyaInventoryRequest) -> PolyaInventoryResult:
    """Compute the Pólya enumeration inventory polynomial."""
    degree, terms = _polya_inventory_data(request.action, request.colors)
    return PolyaInventoryResult(
        action=request.action,
        colors=request.colors,
        degree=degree,
        terms=terms,
    )
