"""Finite stochastic process operation declarations."""

from collections.abc import Callable
from typing import Any

from jacobian._models import StrictModel
from jacobian.catalog._examples import example
from jacobian.catalog.models import MathTool, OperationExample
from jacobian.math.finite_stochastic_processes._models import (
    ConditionalExpectationRequest,
    DoobMartingaleRequest,
    DoobMartingaleResult,
    FiltrationRequest,
    FiltrationResult,
    FromObservationRequest,
    JoinRequest,
)
from jacobian.math.finite_stochastic_processes._operations import (
    compute_conditional_expectation,
    compute_doob_martingale,
    compute_filtration,
    compute_join,
    compute_sigma_from_observation,
)
from jacobian.math.finite_stochastic_processes.values import (
    FiniteRandomVariable,
    FiniteSigmaAlgebra,
)


def _op[
    RequestT: StrictModel,
    ResultT: StrictModel,
](
    operation_id: str,
    title: str,
    description: str,
    request_model: type[RequestT],
    result_model: type[ResultT],
    operation: Callable[[RequestT], ResultT],
    *tags: str,
    examples: tuple[OperationExample, ...] = (),
    version: str = "1",
) -> MathTool[RequestT, ResultT]:
    return MathTool(
        operation_id=operation_id,
        version=version,
        title=title,
        description=description,
        request_type=request_model,
        result_type=result_model,
        run=operation,
        tags=tags,
        examples=examples,
    )


def _rational(numerator: int, denominator: int = 1) -> dict[str, str]:
    return {"num": str(numerator), "den": str(denominator)}


# A fair coin: samples {H, T}, masses 1/2, 1/2.
_SPACE = {
    "samples": ["H", "T"],
    "masses": [_rational(1, 2), _rational(1, 2)],
}

FINIT_STOCHASTIC_PROCESS_OPERATIONS: tuple[MathTool[Any, Any], ...] = (
    _op(
        "probability.finite_sigma_algebra.from_observation.compute",
        "Construct a sigma algebra from an observation map",
        "Return the sigma algebra generated by an observation map Y: Omega -> "
        "labels, whose blocks are equal-value fibers.",
        FromObservationRequest,
        FiniteSigmaAlgebra,
        compute_sigma_from_observation,
        "stochastic-process",
        "sigma-algebra",
        "exact",
        examples=(
            example(
                "coin_observation",
                "Sigma algebra from observing a fair coin.",
                {"space": _SPACE, "observation": ["heads", "tails"]},
            ),
        ),
        version="2",
    ),
    _op(
        "probability.finite_sigma_algebra.join.compute",
        "Compute the join of two sigma algebras",
        "Return the least sigma algebra containing both input sigma algebras. "
        "Under the partition representation, this is the finest partition "
        "that refines both input partitions.",
        JoinRequest,
        FiniteSigmaAlgebra,
        compute_join,
        "stochastic-process",
        "sigma-algebra",
        "exact",
        examples=(
            example(
                "trivial_join",
                "Join of two trivial sigma algebras on a fair coin.",
                {
                    "sigma1": {"space": _SPACE, "blocks": [["H", "T"]]},
                    "sigma2": {"space": _SPACE, "blocks": [["H", "T"]]},
                },
            ),
        ),
        version="2",
    ),
    _op(
        "probability.conditional_expectation.finite.compute",
        "Compute E[X | G] as a block-constant random variable",
        "Return the conditional expectation of a random variable with respect "
        "to a finite sigma algebra. On each block, the value is the "
        "probability-weighted average of X over the samples in that block.",
        ConditionalExpectationRequest,
        FiniteRandomVariable,
        compute_conditional_expectation,
        "stochastic-process",
        "conditional-expectation",
        "exact",
        examples=(
            example(
                "coin_conditional_expectation",
                "Conditional expectation of a coin payoff on the trivial sigma algebra.",
                {
                    "rv": {
                        "space": _SPACE,
                        "values": [_rational(1), _rational(0)],
                    },
                    "sigma": {"space": _SPACE, "blocks": [["H", "T"]]},
                },
            ),
        ),
        version="2",
    ),
    _op(
        "probability.filtration.natural.compute",
        "Compute the natural filtration of observations",
        "Return the natural filtration F_t = sigma(Y_0, ..., Y_t) for each "
        "time t. Each F_t is a finite sigma algebra, and F_t refines F_{t-1}.",
        FiltrationRequest,
        FiltrationResult,
        compute_filtration,
        "stochastic-process",
        "filtration",
        "exact",
        examples=(
            example(
                "single_step_filtration",
                "Natural filtration of a single coin observation.",
                {"space": _SPACE, "observations": [["heads", "tails"]]},
            ),
        ),
        version="2",
    ),
    _op(
        "probability.process.doob_martingale.compute",
        "Compute the Doob martingale M_t = E[payoff | F_t]",
        "Return the Doob martingale of a payoff random variable with respect "
        "to the natural filtration of observations. The result is one tuple "
        "of canonical rational values per time step.",
        DoobMartingaleRequest,
        DoobMartingaleResult,
        compute_doob_martingale,
        "stochastic-process",
        "doob-martingale",
        "exact",
        examples=(
            example(
                "coin_doob_martingale",
                "Doob martingale of a coin payoff process.",
                {
                    "space": _SPACE,
                    "observations": [["heads", "tails"]],
                    "payoff": [_rational(1), _rational(0)],
                },
            ),
        ),
        version="2",
    ),
)

TOOLS = FINIT_STOCHASTIC_PROCESS_OPERATIONS

__all__ = ["TOOLS"]
