"""Exact native kernels for finite stochastic processes."""

from __future__ import annotations

from fractions import Fraction

from jacobian._exact import CanonicalRational

from .values import FiniteProbabilitySpace, FiniteRandomVariable, FiniteSigmaAlgebra

__all__ = [
    "conditional_expectation",
    "doob_martingale",
    "filtration_natural",
    "sigma_algebra_from_observation",
    "sigma_algebra_join",
]


def _index_of(space: FiniteProbabilitySpace) -> dict[str, int]:
    return {s: i for i, s in enumerate(space.samples)}


def _mass(space: FiniteProbabilitySpace) -> list[Fraction]:
    return [mass.as_fraction() for mass in space.masses]


def sigma_algebra_from_observation(
    space: FiniteProbabilitySpace,
    observation: tuple[str, ...],
) -> FiniteSigmaAlgebra:
    """Return the sigma algebra generated by an observation map Y: Omega -> labels.

    Blocks are equal-value fibers.
    """
    if len(observation) != len(space.samples):
        raise ValueError("observation must have one entry per sample")
    fibers: dict[str, set[str]] = {}
    for sample, obs in zip(space.samples, observation, strict=True):
        fibers.setdefault(obs, set()).add(sample)
    blocks = tuple(tuple(sorted(f)) for f in fibers.values())
    return FiniteSigmaAlgebra(space=space, blocks=blocks)


def sigma_algebra_join(
    sigma1: FiniteSigmaAlgebra,
    sigma2: FiniteSigmaAlgebra,
) -> FiniteSigmaAlgebra:
    """Return the least sigma algebra containing both sigma algebras.

    The join is the finest partition that refines both input partitions.
    """
    if sigma1.space != sigma2.space:
        raise ValueError("sigma algebras must share the same probability space")
    blocks: list[tuple[str, ...]] = []
    for b1 in sigma1.blocks:
        for b2 in sigma2.blocks:
            intersection = frozenset(b1) & frozenset(b2)
            if intersection:
                blocks.append(tuple(sorted(intersection)))
    return FiniteSigmaAlgebra(space=sigma1.space, blocks=tuple(b for b in blocks))


def conditional_expectation(
    rv: FiniteRandomVariable,
    sigma: FiniteSigmaAlgebra,
) -> FiniteRandomVariable:
    """Return E[X | G] as a block-constant random variable.

    On each block, the conditional expectation is the probability-weighted
    average of X over the samples in that block.
    """
    if rv.space != sigma.space:
        raise ValueError("random variable and sigma algebra must share the same space")
    idx = _index_of(rv.space)
    masses = _mass(rv.space)
    values = [value.as_fraction() for value in rv.values]
    ce_values: list[CanonicalRational] = []
    for sample in rv.space.samples:
        block = None
        for b in sigma.blocks:
            if sample in frozenset(b):
                block = b
                break
        if block is None:
            raise ValueError("sample not in any block")
        total_mass = Fraction(0)
        weighted_sum = Fraction(0)
        for s in block:
            si = idx[s]
            total_mass += masses[si]
            weighted_sum += masses[si] * values[si]
        ce_values.append(CanonicalRational.from_fraction(weighted_sum / total_mass))
    return FiniteRandomVariable(space=rv.space, values=tuple(ce_values))


def filtration_natural(
    space: FiniteProbabilitySpace,
    observations: tuple[tuple[str, ...], ...],
) -> tuple[FiniteSigmaAlgebra, ...]:
    """Return the natural filtration F_t = sigma(Y_0, ..., Y_t) for each time t."""
    if not observations:
        return ()
    sigmas: list[FiniteSigmaAlgebra] = []
    accumulated: FiniteSigmaAlgebra | None = None
    for _t, obs in enumerate(observations):
        current = sigma_algebra_from_observation(space, obs)
        if accumulated is None:
            accumulated = current
        else:
            accumulated = sigma_algebra_join(accumulated, current)
        sigmas.append(accumulated)
    return tuple(sigmas)


def doob_martingale(
    space: FiniteProbabilitySpace,
    observations: tuple[tuple[str, ...], ...],
    payoff: tuple[CanonicalRational, ...],
) -> tuple[tuple[CanonicalRational, ...], ...]:
    """Return the Doob martingale M_t = E[payoff | F_t] for each time t.

    The payoff is a rational-valued random variable. The result is one
    tuple of canonical rational values per time step.
    """
    if len(payoff) != len(space.samples):
        raise ValueError("payoff must have one entry per sample")
    sigmas = filtration_natural(space, observations)
    rv = FiniteRandomVariable(space=space, values=payoff)
    result: list[tuple[CanonicalRational, ...]] = []
    for sigma in sigmas:
        ce = conditional_expectation(rv, sigma)
        result.append(ce.values)
    return tuple(result)
